### ISSUE TITLE
Recent changes of behavior in browser

### ISSUE THREAD

**Issue by dwyart** [neomutt/neomutt#146]
Hi,

Have been using mutt since 1996 (customizing Sven Guckes' config :-), and Debian unstable version since about 15 years.

Recently mutt has moved more than usual in unstable (based on recent versions of Neomutt) and in the last days, this has annoyed me quite a lot.

The two main annoyances are:

- c? is not opening the browser in $folder anymore but in /var/mail, so to look at archives (stored in $folder), I need to change dir, remove the wrong default value and enter = which is much longer than before.
After a quick look, it looks related to sensible-browser and more-or-less hardcoded. I tried a few manual patches but they had annoying side-effects (notably, maybe related to my second point, using y results in the default entry always being the last one ; also if I "inject" Maildir into LastDir, the browser do not open inside $folder but lists $HOME and I need to press enter to go into $folder).

- when using y to open a mailbox (the incoming mailboxes are in /var/mail), the default entry is always the second one (ie the second mailbox in the list) and I do not understand why. Before it was always on the first entry after pressing y. Again a look at the code did not enlighten me very much...

Any comments on these two points will be much appreciated!

Thanks

Damien

**Comment by P-EB** [comment]
Hi,

The first behaviour (specifically when in "folder" mode) might be adapted if not satisfying neomutt's users, I'll have a discussion about it with @flatcap and others. Feel free to join us on IRC. The main idea is to be able to browse directly the place you're in (eg, if you're connected to an IMAP server, c?/y has to open the imap directory and not $folder).

The second behaviour is also linked to these changes. The idea is, when you get out of a mailbox using c? or y, it's because in general, you want to visit another one, so it places you in the parent box of the one you were reading.

This behaviour is more satisfying for a lot of people, but as it's a big change, it might be annoying. If you have suggestions to tune this, I'll be glad to hear about them.

**Comment by dwyart** [comment]
Thanks for your very fast answer!

Will try to think more about it. Maybe my current reaction is "normal" for a change occuring after many years, and I just need to adapt to the new way. But some tuning around this might also help.

For my 2nd behaviour, I made further tests and what I see is:

- after having visited a mailbox through a choice in "y", typing y again is highlighting this mailbox as default choice, which is quite ok. But at first "y" typing, just after launching mutt, the default highlight is on the second mailbox (in the list corresponding to the mailboxes variable), and I do not see why. It looks like some initialization bug, as if we were adding an extra +1 somewhere... I can definitely live with this one (and my initial description was wrong as the second entry is not *always* chosen but only at first time), but if it is a bug, it might be better to spot it.

Cheers

**Comment by P-EB** [comment]
Yeah, it's because we assume ".." is the first mailbox. Don't you have "../" as a first choice of mailbox?

**Comment by dwyart** [comment]
No, I do not have ".." as first item, and I think it is because y is a macro made of toggle-mailboxes and change-folder. In "mailboxes" mode, we do not browse a folder, so ".." is not present (and I also think this is the difference between examine_mailboxes and examine_directory. So the "skip .." logic should be limited to the directory case.

For the first case, yes, it would be nicer. Not sure about IMAP or other specific case, maybe some users would still prefer something else than $folder.

Thanks again

**Comment by P-EB** [comment]
$folder is unbearable when you're connected to an IMAP server, that's one of the things I wanted to patch. I'll have a look regarding your different demands. :)

**Comment by P-EB** [comment]
I pushed a patch in a specific branch called sensible-browser.

Can you clone the neomutt repo, build this version and tell me if that solves both your issues?

I'm sorry, but I'm not working with "local" mode, so I can't make all tests and I'm not sure to answer appropriately without further tests from you.

**Comment by 4nd3r** [comment]
sorry, but not for my issue :-(

i think it's more sensible that initially highlighted mailbox is the `$spoolfile` or what ever mailbox mutt opens at startup. obviously there are people, who don't open any mailbox at startup (with `imap_passive`), for example don't want trigger password prompt for imap servers while working offline. for them it would be sensible to highlight first mailbox.

also, if `set sort_browser = unsorted` is used, then mailboxes are ordered the way you define them in configuration. with pushed patch, initially 3rd mailbox is highlighted, while my `$spoolfile` is 5th.

hopefully this helps.

**Comment by P-EB** [comment]
I understood your issue.

But it conflicts with the expectation of this one.

@dwyart expects that when using y/c?, he falls directly in $folder. You expect to fall just outside of $spoolfile (the parent directory). There is no simple way I can have these behaviour work together. I can decide that if $spoolfile is defined, then we show the content of the parent dir of $spoolfile with highlight on $spoolfile. If not defined, then we could try to display $folder content.

But in any case, one variable will have precedence on the other.

I pushed something, maybe you should read all the patches to get my point. :)

**Comment by 4nd3r** [comment]
> The second behaviour is also linked to these changes. The idea is, when you get out of a mailbox using c? or y, it's because in general, you want to visit another one, so it places you in the parent box of the one you were reading.

when I get out of mailbox, I expect to see from where I was coming, mutt shouldn't decide for me what I want to "click" next. maybe it's my personal problem, but still :-)

> I pushed something

nope, didn't help. I pass for a moment and see where this issue goes.

**Comment by dwyart** [comment]
Hi!

Thanks for your work on this!
I tested the sensible-branch this morning.

Unfortunately, from thePoV of my first report, nothing has changed:
- c? still goes into /var/mail
- y still focuses on the 2nd entry (not sure why as I see in the code a test for .. which should not match in the list of mailboxes case.

For c? I think it comes from the fact that mutt is initializing $spoolfile to $MAIL at startup. As $MAIL is not empty in my case, I do not benefit from the new code initializing to $folder.

I wil be glad to test any further patches...

Could you maybe run some tests in a fresh VM to better experiment with the local mode if you do not use it at all on your work machines? I guess the "focus on 2nd item" problem should be easy to reproduce.

**Comment by P-EB** [comment]
Do you configure spoolfile or folder in your .muttrc ?

**Comment by dwyart** [comment]
To further comment on the thread as a whole, two additional points:
- I understand people like to browse in the parent folder of $spoolfile, but this is what y does.
- Historically, c? has been browsing in $folder for 20+ years, so I do not agree to change it unconditionnally to spoolfile by default, even if some users would prefer that. It should be something configurable.

I do not see the point in y and c? browsing the same folders: they are different commands so should not do the same thing (they are not aliases). In my habits, being able to broswe the incoming mailboxes with y and the archives with c? has been working really well.

**Comment by dwyart** [comment]
$folder is configured (but I think I equals to the default value anyway, ~/Mail) in .muttrc, but NOT $spoolfile. As the doc says, it is automagically initialized to $MAIL by default when mutt starts.

**Comment by dwyart** [comment]
For my previous comment, I missed the fact that some people my have $mailboxes containing files in different folders (this is not my case). So the "parent folder" might not be unique and equal to /var/mail.

**Comment by 4nd3r** [comment]
> I understand people like to browse in the parent folder of $spoolfile, but this is what y does.
Historically, c? has been browsing in $folder for 20+ years, so I do not agree to change it unconditionnally to spoolfile by default, even if some users would prefer that. It should be something configurable.

I agree! 

>> The second behaviour is also linked to these changes. The idea is, when you get out of a mailbox using c? or y, it's because in general, you want to visit another one, so it places you in the parent box of the one you were reading.

> when I get out of mailbox, I expect to see from where I was coming, mutt shouldn't decide for me what I want to "click" next. maybe it's my personal problem, but still :-)

As a sidenote, I expect this behaviour with `y`, not `c?`. Maybe this clears up things a bit?

**Comment by P-EB** [comment]
y a macro. It Is barely "c?\t", so, no, it's not exactly what I call a different command. I can get that you'd expect two different behaviours, so I just made a patch to give precedence on $folder if it exists in the config. c? should display the content of $folder now. About y, it does c? and then toogle mailboxes, I can't be sure about what it'll display in your case, because I don't use mutt for other things than IMAP. Can you test it for me please? :)

On a side note, initializing Spoolfile to $MAIL seems totally inaccurate, as it contains an email address, which is not useful as a spoolfile (usually /var/spool/mail/$user). I don't know why this legacy thing is still there.

**Comment by dwyart** [comment]
Yes, I confirm that with the latest patch, c? goes back to "historical" behavior, so this fills my initial expectation :) Thanks!
You are also right on c? and y being close, I was more reasoning on their "effect" but their definitions are clearly not orthogonal.

I still get strange highlight positions in y (2nd position most of the time, but last one after doing c? and browsing a mailbox inside $folder), will try to investigate more on that...

**Comment by P-EB** [comment]
Yeah, as said, I tried to change c? behaviour, but side effects on y are plausible as they rely on same methods for a big part of their jobs.

I'll also have a look on that.

**Comment by P-EB** [comment]
@dwyart it should be fixed. Please, tell me if that's ok.

**Comment by dwyart** [comment]
Here is where I stand right now:
- I tried to set menu->current = 0; in the buffy case (browsing mailboxes with y) and this worked well (always at first item), but I realize it was a hack and it skips completely sensible browsing... But at leasts it behaves as in vanilla mutt, which is what I am used to.
- with your latest patch (and without my previous modification), it is a bit better, but after browsing a mailbox through c?, default highlight in y is at the end which looks wrong. But at first call of y we are on first entry which is ok.
- I still wonder if your current approach is going into the right direction. It still feels a bit hackish for a not huge benefit. In fact, I am still quite far from the usual mutt behaviour, because even if c? goes into $folder the first time, later on, after some incoming mail reading, if I need to read archives, c? will stay in /var/mail, so I still need to manually go to $folder. In short, I lose the "shortcut bookmark to $folder" feature of c? in standard mutt.
- so for my normal work I am back to vanilla mutt for now, I guess I am really too much used to these habits.

What do you think? Wouldn't it be better to keep two modes: the classical one (which goes down to disabling sensible browsing) and your current implementation (in neomutt branch), not dealing with $folder at all? Then a setting would allow a real choice, which is not the case even with the experimental branch.

Thanks!

**Comment by P-EB** [comment]
There is an important difference between "keeping a behaviour because I'm used to it" and "rolling back to a behaviour because there is no logic or it's buggy".

c? doesn't seem to be a bookmark to $folder. Or at least, the documentation in mutt never introduced such an idea, as far as I was able to see. Since I switched to mutt, I'm always annoyed by the fact "c?" hits me back to $folder or so for no reason when I'm three directories down.

Here are my thoughts.
- There is a clear bug with the "current" position of menu, we have to narrow it down before going any further
- I'm not against making a configuration variable, but I really think this feature is an improvement, especially if we fix all those bugs for good.
- I agree having a shortcut to go back up to $folder would be good. Maybe we could design a binding to handle that in browser mode (not in mailbox mode).

**Comment by dwyart** [comment]
OK for me with your proposals, I will happily continue to test your experimental branch.

As an end-user, it is not always easy to abstract from habits, so thanks for suggesting something broader.

**Comment by P-EB** [comment]
@flatcap my second point is really a "big" matter regarding backward compatibility. Do we want to support old users' habits? I'm willing to do so, but I'd rather get some opinions from you and maybe other users. :)

@dwyart regarding the third point, which keybinding would you suggest?

**Comment by dwyart** [comment]
As $folder can be shortened as = in prompts, maybe the = key in browser mode to go back to $folder would make sense.

I confirm the latest patch solves the positioning issue. Thanks!

**Comment by P-EB** [comment]
Excellent idea, thanks for this input, I didn't think about it!

I'll keep you posted.

**Comment by P-EB** [comment]
@dwyart there, I pushed a commit.

When in browser mode (not in mailboxes mode, so it won't work with 'y'), you can hit '='.

Tell me if that fulfills your expectations.

Cheers

**Comment by dwyart** [comment]
It seems to work and I think after some time I could get used to it.

It would be useful, I think, to have = appear in the list of shortcuts displayed in brower mode (at the bottom of the screen), and not only in help mode.

I still see some side effect on the highlight posiiton:
If I go to a mailbox from y, and from this mailbox, call c? then = and read some mailbox with archives, a new call on y still highlights the entry of the first read mailbox. As my last mailbox used was not that one but the one with archives in $folder, I would prefer the default highlight after y to be first line (like it doesn if after starting mutt, I use c?, browse an archive, and then press y).
But that might contradict a bit the sensible browser idea, so not 100% sure.

Having = in folder browsing mode is nice, and is a good middle ground between the old behavior and sensible browsing.

**Comment by 4nd3r** [comment]
@P-EB hmm, looks like `y` behaves OK (for me) now :-)

**Comment by P-EB** [comment]
@dwyart thanks for your feedback. About your "issue" with c? and y combos, I can't tell what would be better.

I'll discuss with @flatcap and others dev about adding this option to disable sensible-browsing, but if you agree to try some time with the current behaviour, that'd help me to see if this backward compatibility is really necessary of is users could get along with my changes.

I'll add '=' tip in shortcuts.

Cheers!

**Comment by P-EB** [comment]
A merge-ready/sensible-browser branch is ready to be merged in the next release.

**Comment by flatcap** [comment]
@dwyart @P-EB @4nd3r 
Thanks for all your (detective) work on this.  I've merged the fixes.
I've closed **this** issue, but it probably isn't the end.

Next, the sensible-browser needs documenting.
I have some notes and a few simple "use cases".
I'll open a new issue when I've had a think and typed them up.

**Comment by bucko909** [comment]
Am I correct in thinking that the effect of the change is similar to linking my spool file *into* my `folder` and setting `spoolfile=$folder/spoolfile`? This is the approach I have taken to restoring the old behaviour before finding this bug.
