### ISSUE TITLE
Bogus "New mail" in every mailbox

### ISSUE THREAD

**Issue by hvkls** [neomutt/neomutt#1629]
## Expected Behaviour

New mail should be reported in mailboxes with new mail only.

## Actual Behaviour

On Mac OS Mojave (10.14.4) and neomutt [https://github.com/neomutt/neomutt/commit/92885b5d46e81007c0a6a699121e5693bd76165a](https://github.com/neomutt/neomutt/commit/92885b5d46e81007c0a6a699121e5693bd76165a), all of my 79 mailboxes (MBOX format) report new mail, while there is only one mailbox where this is actually true. 

When I open the respective mailboxes, the number of "new mail" boxes decreases. But when I quit and restart neomutt, again all of them have the bogus 'new mail'.

## When did it start to happen?

Sorry, all I can remember is I used to compile neomutt with --enable-buffy-size (was that the name?) and it worked fine back then. 

## NeoMutt Version

NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 18.5.0 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libiconv: 1.15
libidn: 1.35 (compiled with 1.35)
hcache backends: kyotocabinet

Compiler:
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: --prefix=/opt --sysconfdir=/opt/etc --with-gpgme=/opt/local --notmuch --with-ui=ncurses --with-ncurses=/opt/local --enable-locales-fix --with-ssl=/opt/local --gpgme --gss --smime --gnutls --sasl --kyotocabinet --with-lua=/opt/local --enable-debug

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -I/opt/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen -futimens +getaddrinfo 
  +gnutls +gpgme +gss +hcache -homespool +idn +locales_hack +lua +meta 
  -mixmaster +nls +notmuch -openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead

**Comment by flatcap** [comment]
I think I know what this is, but not what's changed so that it's _just_ started happening.

NeoMutt asks IMAP servers for various attributes about mailboxes:
- `UNSEEN` - real, new messages
- `RECENT` - 'something' changed recently

(Neo)Mutt combines the two into the 'new' flag -- I've no idea why.

Please can you try commenting out the 'new' line:
https://github.com/neomutt/neomutt/blob/92885b5d46e81007c0a6a699121e5693bd76165a/imap/command.c#L874-L878

**Comment by hvkls** [comment]
No, it doesn't help. I could spot a message '-999 is not a Mailbox' (might have been -9999)

**Comment by flatcap** [comment]
> I used to compile neomutt with --enable-buffy-size (was that the name?)

I don't remember that name (and I can't find it, or anything like it, anywhere).

>  message '-999 is not a Mailbox' (might have been -9999)

Please can you run with logging enabled and see where the message is coming from.

Or better still, if you have the time, `git bisect` to see when the problem started.

Thanks.

**Comment by hvkls** [comment]
Here's an abbreviated log:

[2019-04-02 16:38:45] NeoMutt-20180716-1432-ae87f8 debugging at level 3
[2019-04-02 16:38:45]<M> log_file_open() Debugging at level 3 to file '/Users/hvkls/.neomuttdebug0'
[2019-04-02 16:38:45]<2> mutt_window_reflow() entering
---------------------
[2019-04-02 16:38:45]<M> mutt_progress_update() Reading /var/mail/hvkls... 0
[2019-04-02 16:38:45]<3> is_from() month=9, day=2, hr=21, min=57, sec=43, yr=118.
[2019-04-02 16:38:45]<2> parse_parameters() 'boundary=Apple-Mail-CA96B45D-A1C7-4CB7-BBC4-1178FC6D21AD'
[2019-04-02 16:38:45]<2> parse_parameters() parse_parameter: 'boundary' = 'Apple-Mail-CA96B45D-A1C7-  4CB7-BBC4-1178FC6D21AD'
[2019-04-02 16:38:45]<3> is_from() month=9, day=1, hr=18, min=26, sec=7, yr=118.
[2019-04-02 16:38:45]<2> parse_parameters() 'charset=UTF-8; format=flowed'
[2019-04-02 16:38:45]<2> parse_parameters() parse_parameter: 'charset' = 'UTF-8'
---------------------
2019-04-02 16:38:53]<M> mutt_mailbox_list() New mail in =1, =2, =3, =4, =5, ...
[2019-04-02 16:38:53]<2> mutt_window_reflow() entering
[2019-04-02 16:38:53]<3> mutt_index_menu() [1229]: Got op 98
[2019-04-02 16:38:53]<M> mutt_mailbox_list() New mail in =6, =7, =8, =9, ...
[2019-04-02 16:38:53]<2> mutt_window_reflow() entering

**Comment by hvkls** [comment]
git bisect start b37a784 6a147a6

[...]

Bisecting: 10 revisions left to test after this (roughly 4 steps)
[ac8c4ef6deacfc04d43c9b036d7eae45864d8805] add Account

[The above was last good one, as far as I can tell]

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
1ec2775ba70d434795507dbe8bb77aa6f1cfbf1a
3e5a7272f108fa22d75761a89d9f7a5d12c61b4e
60e64c915ac6679d33f8e9496def202b7c23dcc5
ef5b454f7825db2ca65b8ff1da88c3b79279f238
677b7d46f0002c84711a52fef88d3bed86eb8041
d803e7f6104321adb4a86465e7a173711599f93f
600525ada78cac9db930f143aea72af72dd2f632
6023d86ab74771e7cbb48226809c926436e0af15
a038a8a62a1240507be379e8a7ca4e0a60fed025
b8ff2ad1f362ffa18f1a5a209d51dd1e77b95974
6940fb2c21c4c99265003d3522d4b0b4b5a38204
d29c062d9324e8d5c2d78cb8b0d5fe046f64c806
829c5c7b1c1d1183fe2cba7f9c76ef81a93fc614
87f487c35b1720e6c69a205c969d4e0e5ddf762f
0ae43f29b113de7787895ccbfe7ed393e8ed22d0
eba15daafb8c2a614992aeeaaf263d964e41a1ff
23dc0841d5f3a44fb8323e1a09aec56daa39a22d
a84149e0fd3563d64e55b348d90b3c4e0ee5e23a
e46ba978910c911ec57aea7fb7735a5a941717c5
ec83754093baced2517bdd34ff99f58c8725499f
5e41e5ea10865c865d9e70f932cd0037a8881cb5
We cannot bisect more!

**Comment by hvkls** [comment]
FYI, ac8c4ef6deacfc04d43c9b036d7eae45864d8805 crashes on NNTP, but new mail is displayed OK.

**Comment by gahr** [comment]
Is this still happening with a fresh master?

**Comment by hvkls** [comment]
Unfortunately yes :(

**Comment by gahr** [comment]
Can I see an excerpt of your config where you specify folder and mailboxes and an example of how your mbox files are organized?

**Comment by hvkls** [comment]
Sure.

mailboxes ! `ls -1 $HOME/Mail/* | egrep -v "(gz|IO.sent|nntp|nntp.sent|Drafts|Sent|Templates|Trash|msgid.cache|sbd|sdb|save|save.nntp|save.nntp.mac|spc)" | tr "\012" " "`

which lists about 83 files in mbox format, in a single line.

**Comment by gahr** [comment]
What is your `folder` setting, and which key sequence do you type (please expand macros, if any) that leads to where you see the bogus new mail count?

**Comment by hvkls** [comment]
It "just happens", even with a minimal setup, with the most recent version (see above for details on older, working versions).

/opt/src/neomutt/neomutt -F ~/.mutt/mutt.debug

# ~/.mutt/mutt.debug
mailboxes ! `ls -1 $HOME/Mail/* | egrep -v "(gz|IO.sent|nntp|nntp.                                    sent|Drafts|Sent|Templates|Trash|msgid.cache|sbd|sdb|save|save.nntp|save.nntp.mac|spc)" | tr "\012" " "`
set check_mbox_size=yes
set folder=$HOME/Mail
set mark_old=no
set mbox_type=mbox

The permissions on $HOME/Mail are 0700, and 0600 on $HOME/Mail/*

**Comment by flatcap** [comment]
Hmm... I see it now, but I also see the same behaviour in Mutt.
It's the `set check_mbox_size=yes` that's causing trouble.
In the docs, it says:

> This variable is unset by default and should only be enabled when new
> mail detection for these folder types is unreliable or doesn't work.

Do you really need it?

Setting this (below), means I get an immediate check on the contents of the mbox and stats in the sidebar.

```
set check_mbox_size           = no
set mail_check_stats          = yes
set mail_check_stats_interval = 5 
```

**Comment by hvkls** [comment]
FYI: I don't use the sidebar and haven't changed my settings in years.

Try this please:

set status_format = "%b"
set mail_check_stats          = yes
set mail_check_stats_interval = 5 

If I "set check_mbox_size           = no" with that, it returns "82" mailboxes. When I "c"hange to one, the number decreases to "81". Whether I make or don't make changes, "q"uit with or without saving, the number will be "82" on the next run.

If I "set check_mbox_size           = yes" instead (and set "mailboxes" thereafter, as documented), it returns "82" mailboxes plus "New mail in =" and so on. 

When I press "c"hange within 5 secs., it returns the first mbox in the list. When I "c"hange to it, the number decreases to "81". Whether I make or don't make changes, "q"uit with or without saving, the number will be "82" on the run. 

After 5 secs., "c"hange returns nothing (= no new mail). When I "c"hange to one of the mboxes, the number decreases to "81". Whether I make or don't make changes, "q"uit with or without saving, the number will be "82" on the next run.

**Comment by flatcap** [comment]
Thanks for your patience, @hvkls.
Please give the branch `[devel/issue-1629]` a try.

One of the MXAPI refactors meant we weren't distinguishing between 'Success, no mail' and 'Success, new mail'.

The status bar now shows the correct number of mailboxes with unread mail.
Pressing <kbd>.</kbd> `<mailbox-list>` shows their names.
Pressing <kbd>c</kbd> `<change-folder>` suggests the next with new mail.

**Comment by hvkls** [comment]
[devel/issue-1629] with "set check_mbox_size = no" shows just the mailboxes with new mail now.

However: 

A previously visited mailbox with "old" new mail (by which I mean "N" flagged msgs) is reported as containing "new mail". 

When I change to the first mbox with new mail, its state is correctly set to "no new mail". But changing to the next mailbox with new mail resets/restores the state of the first mailbox to "new mail".

Besides, the startup process takes 4 seconds (reportedly reading mailbox !, the spoolfile), compared to the usual startup duration of less than 1 second.

**Comment by hvkls** [comment]
When I change to that "new mail" mbox now, the state changes to "no mail". 

If there are "N" messages when I quit neomutt, the mbox keeps (respectively, restores) the "new mail" status; with no "N" messages, it becomes "no mail". 

If I start with no "N" messages and "no mail", flag one msg w/ "N", and quit, neomutt reports "Mailbox is unchanged". On the next start, the mbox has got "new mail".

**Comment by flatcap** [comment]
I've been comparing Mutt, Old NeoMutt and Latest NeoMutt.
Your bug is just one of several discrepancies.
I'll see what I can do.

**Comment by hvkls** [comment]
I have discovered that the slow opening is triggered by "set mail_check_stats=yes", even with NeoMutt 20180716!

The compilation of  https://github.com/neomutt/neomutt/commit/ac7ec7af75328e8fdc74a5466fadcc26796ecf33 fails,

```
cc -I/opt/include -I/opt/local/include -I/opt/local -I/var/include -I/usr/include -I/usr/local/include -I/var/include -I/var -I/usr/include/gnutls -I/usr/lib/ssl/include -I/opt/local/include/ncursesw -I/opt/local/include/openssl -I/usr/include/ncursesw -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/var/stash/include -I. -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -I/opt/include -DNCURSES_WIDECHAR -I. -I. -Wall  -I./test -MT mutt_logging.o -MD -MP -MF mutt_logging.Tpo -c -o mutt_logging.o mutt_logging.c
cc -I/opt/include -I/opt/local/include -I/opt/local -I/var/include -I/usr/include -I/usr/local/include -I/var/include -I/var -I/usr/include/gnutls -I/usr/lib/ssl/include -I/opt/local/include/ncursesw -I/opt/local/include/openssl -I/usr/include/ncursesw -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/var/stash/include -I. -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -I/opt/include -DNCURSES_WIDECHAR -I. -I. -Wall  -I./test -MT mutt_mailbox.o -MD -MP -MF mutt_mailbox.Tpo -c -o mutt_mailbox.o mutt_mailbox.c
mutt_mailbox.c:91:1: error: version control conflict marker in file
<<<<<<< HEAD
^
1 error generated.
make: *** [mutt_mailbox.o] Error 1
```

**Comment by hvkls** [comment]
Sorry – the compilation of https://github.com/neomutt/neomutt/commit/ac7ec7af75328e8fdc74a5466fadcc26796ecf33 works in a freshly cloned directory. 

The number of mailboxes with new mail is reported correctly and decreases as expected when no "N" flagged messages are left in the mbox; all mboxes with "N" flag are reported as containing new mail the next time neomutt is started.

**Comment by flatcap** [comment]
> the slow opening is triggered by "set mail_check_stats=yes",

thanks for the info

> even with NeoMutt 20180716!

Hmm...

**Comment by flatcap** [comment]
I've updated branch [[devel/issue-1629]](https://github.com/neomutt/neomutt/tree/devel/issue-1629).
It fixes a lot of confusion between meanings of "new".

- The Mailbox **new** indicator (`%N` browser, sidebar) is fixed.
- Status `%b` is a count of these 'fresh' Mailboxes
- Fixed `$change_folder_next` behaviour
- Fixed sidebar **new** colour

Please can you give it a try.
Thanks.

**Comment by hvkls** [comment]
It works for me with these settings:

set alias_format = "%4n %2f %t %-10a   %r"
set attach_format = "%u%D%I %t%4n %T%.40d%> [%.7m/%.10M, %.6e%?C?, %C?, %s] "
set beep=yes
set check_mbox_size=yes
set check_new=yes
set connect_timeout=30
set date_format = "!%a, %b %d, %Y at %I:%M:%S%p %Z"
set folder=$HOME/Mail
set folder_format = "%2C %t %N %F %2l %-8.8u %-8.8g %8s %d %i"
set index_format = "%4C %3M%Z %[%y%m%d] %-17.17F (%3l) %s"
set mail_check_recent=yes
set mail_check_stats=yes
set mail_check_stats_interval=5
set mark_old=no
set mbox_type=mbox
set status_format = "%b"
set time_inc=0
set timeout=35

mailboxes ! `ls -1 $HOME/Mail/* | egrep -v "(gz|IO.sent|nntp|nntp.sent|Drafts|Sent|Templates|Trash|msgid.cache|sbd|sdb|save|save.nntp|save.nntp.mac|spc)" | tr "\n" " "`

**Comment by flatcap** [comment]
Brilliant!  Sorry it took so long to sort out.
Thanks for all your explanation.

**Comment by hvkls** [comment]
With neomutt-2019-11-11, the problem is back, in a new way: Mailboxes with new mail are not announced, neither when neomutt starts nor while it's running.

**Comment by flatcap** [comment]
_mea culpa_
@hvkls Please can you give #1963 a try.
I've given it a good thrashing with mbox, maildir and imap folders,
and they all behave correctly now (or at least they behave the same way :-)

**Comment by hvkls** [comment]
I downloaded the patch for and installed it with "patch -p1 < 1963.patch".

Unfortunately, I see no effect.

What I had noticed before patching: New mail is announced when it arrives in the current mbox, but not in other mboxes. The patch hasn't changed this.

**Comment by hvkls** [comment]
More info: If I keep neomutt-2019-11-11-patch1963 open and run 2018-07-16 in a different window, and new mail arrives, 20180716 detects it instantly. After 20180716 has detected it, it is also announced in neomutt-2019-11-11-patch1963. HTH :)

**Comment by hvkls** [comment]
Any news on this? :(

**Comment by flatcap** [comment]
Nope.
Your original bug, which was serious, is fixed again.
What you describe above is a different bug and while it needs fixing, it's not the highest priority thing I have to deal with.

**Comment by hvkls** [comment]
There's some logic in what you're saying, however, 'too much' new mail is, from the user's point of view, as good or as bad as 'not enough' new mail. 

I'll go back to 665a0279 (thanks for updating the releases site) and wait for the next stable release.
