### ISSUE TITLE
Master is extremely laggy

### ISSUE THREAD

**Issue by rgrinberg** [neomutt/neomutt#50]
Just updated to master and neomutt is unusable. Any kind of cursor motion takes around 1 second to complete.

**Comment by karelzak** [comment]
I agree. Today I switch from mutt-kz to neomutt/master and the difference is pretty visible -- all works as expected, but UI is "lazy and tired".

**Comment by flatcap** [comment]
OK, thanks guys.  Let me test some ideas...

**Comment by flatcap** [comment]
I've pushed a temporary fix: https://github.com/neomutt/neomutt/tree/issue/50
The mailbox checks were getting called **way** too often.
It seems fairly responsive with my demo large mailboxes.
Please can you give it a try.

**Comment by rgrinberg** [comment]
@flatcap your patch seems to bring back the snapiness to my neomutt. Thanks!

**Comment by karelzak** [comment]
Seems better now. Thanks.

**Comment by flatcap** [comment]
Good.  Sorry about that.

**Comment by rgrinberg** [comment]
FYI it's a lot snappier now but still doesn't feel as snappy as the old neomutt.

**Comment by flatcap** [comment]
@rgrinberg 
Everything was better in the old days :-)

I'm still working on this...

**Comment by rgrinberg** [comment]
At least it's still faster than gmail :)

Please don't rewrite mutt in js...
