### ISSUE TITLE
No UTF8 support for subject line?

### ISSUE THREAD

**Issue by andreas-bulling** [neomutt/neomutt#589]
Hi,

UTF8 support works fine for neomutt in my terminal (iTerm2 on MacOSX) except for the subject line: When I start a new email and try to enter a German umlaut in the subject I only end up getting garbage.

I am using NeoMutt 20170428 (1.8.2)

**Comment by flatcap** [comment]
I've just had a quick look and everything seems fine (for me a a couple of others on IRC).
I've tested extended ascii and a range of Unicode characters (both sending and receiving).

What's your locale set to in the terminal?
What's `charset` set to in mutt -- `mutt -D | grep charset`

**Comment by andreas-bulling** [comment]
Thanks for your quick reply. As I said, message body is not a problem, only subject line (after pressing "m") causes problems.

Output of `mutt -D | grep charset`:
```
assumed_charset=""
attach_charset=""
charset="utf-8"
config_charset=""
send_charset="us-ascii:utf-8"
```

**Comment by andreas-bulling** [comment]
Just tried something else: If I press button "[", with the German "input source" enabled in MacOSX, I get a "ü" in the terminal but the subject line shows "C<". Is this some modifier key issue? But, again, if I then edit the message in nvim everything is fine, i.e. the right characters are sent to/by the terminal.

**Comment by riesebie** [comment]
* andreas-bulling <notifications@github.com> [2017-05-23 09:23 -0700]:

> Thanks for your quick reply. As I said, message body is not a problem, only subject line (after pressing "m") causes problems.
> 
> Output of `mutt -D | grep charset`:
> ```
> assumed_charset=""
> attach_charset=""
> charset="utf-8"
> config_charset=""
> send_charset="us-ascii:utf-8"

What happens if you set
send_charset="utf-8"
?
-- 
  The path to source is always uphill!
                                -unknown-

**Comment by andreas-bulling** [comment]
no change :/

**Comment by gahr** [comment]
@andreas-bulling do you happen to have `mime_subject` unset?

**Comment by andreas-bulling** [comment]
I just typed some German umlaute in another terminal and tried to copy them into the subject line - doesn't work, I directly receive garbage

**Comment by gahr** [comment]
That is surprising. Does that happen with any input forms (say, `To:`) or just with `Subject:`?

**Comment by andreas-bulling** [comment]
Yes, this also happens for the `To:` input form and I also can't type German umlaute there either as I just noticed (never tried before)

**Comment by gahr** [comment]
@andreas-bulling any chance you could try that with the vanilla Terminal app from Mac OSX? Just to make sure it's Mutt's problem and not iTerm2's.

**Comment by andreas-bulling** [comment]
same behaviour/problem with the vanilla terminal app

**Comment by gahr** [comment]
Thanks for the info so far, I will try to reproduce it.

**Comment by andreas-bulling** [comment]
Let me know if I can be of any other help - happy to help if I can!

**Comment by gahr** [comment]
I have tried with a fresh checkout of `master` on macOS Sierra 10.12.4 and I cannot reproduce.

- `./prepare` called with `--disable-doc` as the only argument
- gettext from [brew](https://brew.sh/)
- minimal `.muttrc` with only `spoolfile`set to a temporary file

```sh
$ otool -L ./mutt
./mutt:
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.65.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.51.1)
```

```sh
% locale
LANG=
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL="en_GB.UTF-8"
```

I am able to paste `κόσμε` (the first example of utf-8 text that google gave me) into any input forms.

Could you please:
* try with a similar minimal setup
* tell me what is different in your setup? Especially, where did you get the dependencies from (macports, brew, ...)?

**Comment by andreas-bulling** [comment]
I will try this over the weekend, here is the output of otool for a starters...

```
otool -L ./mutt
./mutt:
	/usr/local/opt/s-lang/lib/libslang.2.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libsasl2.2.dylib (compatibility version 3.0.0, current version 3.15.0)
	/usr/local/opt/tokyo-cabinet/lib/libtokyocabinet.9.dylib (compatibility version 9.0.0, current version 9.11.0)
	/usr/local/opt/libidn/lib/libidn.11.dylib (compatibility version 18.0.0, current version 18.16.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/notmuch/lib/libnotmuch.4.dylib (compatibility version 4.4.0, current version 4.4.0)
```

**Comment by andreas-bulling** [comment]
OK, I tried, i.e. I did exactly the same but still had the same issue. I installed everything using homebrew.

```
[andreas:~/src/neomutt]$ otool -L ./mutt                                                                                                    (master)
./mutt:
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/local/opt/libidn/lib/libidn.11.dylib (compatibility version 18.0.0, current version 18.16.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

```
[andreas:~/src/neomutt]$ locale                                                                                                             (master)
LANG=
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL="en_GB.UTF-8"
```

**Comment by rlue** [comment]
I'm having the same problem, but not just on the subject line. 

Specifically, I just upgraded to v1.8.3 via homebrew. Not sure which version I was running before that, but I believe it was v1.8.2. All Chinese characters are replaced by question marks, both in subject lines and in message bodies. Same text was rendered properly prior to the upgrade. Also running Mac's vanilla Terminal.app. 

Also unable to enter Chinese characters in Editor Mode (_e.g.,_ in the subject line when composing new mail) either. I just get a system beep and no character input.

Output of `mutt -D | grep charset` is

```
assumed_charset=""
attach_charset=""
charset="us-ascii"
config_charset=""
newsgroups_charset="utf-8"
send_charset="us-ascii:iso-8859-1:utf-8"
```

For `locale`, it's

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Also happy to contribute whatever's necessary to a solution.

**Comment by andreas-bulling** [comment]
you can still enter Chinese characters in the terminal/editor when composing?

**Comment by rlue** [comment]
That's correct

**Comment by rlue** [comment]
FWIW, I've confirmed that this problem happens with a minimal configuration (_i.e.,_ bare except for specifying maildirs), with neomutt installed against HEAD.

Potentially also of interest is the way the latest version of Neomutt garbles `U+2500` (BOX DRAWINGS LIGHT HORIZONTAL) as `T~@` on my status line. Here's my `status_format` setting:

```
set status_format = "───[ Folder: %f ]───[%r%m messages%?n? (%n new)?%?d? (%d to delete)?%?t? (%t tagged)? ]───%>─%?p?( %p postponed )?───"
```

which ordinarily appears as:

```
───[ Folder: ~/Mail/<<Gmail>> ]───[ 9 messages ]───────────────────────────────
```

In the latest version of neomutt, it looks like:

```
T~@T~@T~@[ Folder: ~/Mail/<<Gmail>> ]T~@T~@T~@[ 9 messages ]T~@T~@T~@
```

**Comment by flatcap** [comment]
@rlue  If the line chars aren't rendering properly, then you may have a build problem.
It's important to build against the **wide** version of ncurses (look for a 'w' in the package name).
Without this, NeoMutt will only display ASCII.

@andreas-bulling  Sorry we haven't been able to help.
NeoMutt definitely works with extended ASCII and full Unicode.

**Comment by rlue** [comment]
@flatcap, thanks for following up. Is it possible to specify these build options via homebrew?

How can I tell what version of ncurses my neomutt was built against? I'm not quite sure I don't see any reference to `ncurses` or `ncursesw` in `brew info neomutt` or `mutt -v`:

### `brew info neomutt`

```
neomutt/neomutt/neomutt: stable 20170609, HEAD [pinned at 20170428]
Bringing together all the Mutt Code
http://www.neomutt.org/
Conflicts with:
  mutt (because both install mutt binaries)
  tin (because both install mmdf.5 and mbox.5 man pages)
/usr/local/Cellar/neomutt/20170428 (113 files, 3.3MB) *
  Built from source on 2017-06-04 at 23:53:12 with: --with-sidebar-patch --with-notmuch-patch
From: https://github.com/neomutt/homebrew-neomutt/blob/master/Formula/neomutt.rb
==> Dependencies
Build: autoconf ✔, automake ✔, gettext ✔, docbook ✔, docbook-xsl ✔
Required: openssl ✔, tokyo-cabinet ✔
Optional: gpgme ✘, libidn ✔, s-lang ✘
==> Requirements
Build: git ✔
==> Options
--with-debug
        Build with debug option enabled
--with-gpgme
        Build with gpgme support
--with-libidn
        Build with libidn support
--with-notmuch-patch
        Apply notmuch patch
--with-s-lang
        Build against slang instead of ncurses
--HEAD
        Install HEAD version
```

### `mutt -v`

```
NeoMutt 20170428 (1.8.2)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Darwin 15.3.0 (x86_64)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Apple LLVM version 7.0.0 (clang-700.0.57.2)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

Configure options: '--disable-dependency-tracking' '--disable-warnings' '--prefix=/usr/local/Cellar/neomutt/20170428' '--with-ssl=/usr/local/opt/openssl' '--with-sasl' '--with-gss' '--enable-imap' '--enable-smtp' '--enable-pop' '--enable-hcache' '--with-tokyocabinet' '--disable-nls' '--enable-sidebar' '--enable-notmuch' '--disable-debug' 'CC=clang'

Compilation CFLAGS: -g -O2

Compile options:
+CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME -CRYPT_BACKEND_GPGME
-DEBUG +DL_STANDALONE -ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET -HAVE_FUTIMENS
+HAVE_GETADDRINFO +HAVE_GETSID +HAVE_LANGINFO_CODESET +HAVE_LANGINFO_YESEXPR
+HAVE_LIBIDN +HAVE_META -HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR
+HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS -USE_COMPRESSED +USE_DOTLOCK
+USE_FCNTL -USE_FLOCK -USE_FMEMOPEN +USE_GSS +USE_HCACHE +USE_IMAP -USE_LUA
+USE_NOTMUCH -USE_NNTP +USE_POP +USE_SASL +USE_SETGID +USE_SIDEBAR +USE_SMTP
-USE_SSL_GNUTLS +USE_SSL_OPENSSL
-DOMAIN
-MIXMASTER
-ISPELL
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20170428/share/mutt"
SYSCONFDIR="/usr/local/Cellar/neomutt/20170428/etc"
EXECSHELL="/bin/sh"
...
```

(Followed by a list of installed patches.)

**Comment by rlue** [comment]
Very weird, I just came back to this after having `brew pin`ned neomutt v1.8.2 (20170428) for the past month or so. Can't explain what changed, but now neomutt v1.8.3 (20170609) is rendering wide unicode characters totally fine! 

Consider my vote on this issue withdrawn.

**Comment by flatcap** [comment]
@rlue Great, thanks for letting us know.

We've met quite a few people who built their own NeoMutt only to find that it was against the non-wide version of ncurses. 

> know how to tell which version of ncurses my neomutt

Good question.  You're right, `mutt -v` isn't helpful.

Recently though, we changed the build to **require** the wide version of ncurses.
Hopefully this will fix things for good :-)

**Comment by andreas-bulling** [comment]
@flatcap I very much appreciate your efforts but I definitely still have this issue on two different machines. Anything else I can try/check to help you guys go deeper into the issue?

**Comment by andreas-bulling** [comment]
Hi - it's been a while but I haven't given up on trying to fix this problem. One new piece of information. When I type in `:set &charset ?charset` the output is `charset="us-ascii"` although I have set `export LANG=en_US.UTF-8` or `LC_CTYPE=en_US.ISO-8859-1`

**Comment by andreas-bulling** [comment]
and I also found the most likely reason for this:
https://stackoverflow.com/questions/13088537/mutt-garbage-characters-in-mail-titles

`otool -L `which mutt` | grep curses`
gives me
`/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)`

**Comment by gahr** [comment]
Try setting `LC_ALL`

**Comment by andreas-bulling** [comment]
Thanks for the suggestion. I tried that and the command now return `utf-8`.
But I still can't put any Umlaute in the subject line and subjects from other emails with Umlaute still don't get shown properly. So I am guessing it could still be the libncurses problem...

**Comment by benne** [comment]
So, I had the same problem, and found my way around this. I am not sure ff this is a viable solution, but for now I can read my emails - and that is a big plus in my book.

I ended up installing ncurses (that also contains libncursesw) through homebrew, and modifying the recipe using "brew edit", adding --with-curses=/usr/local/opt/ncurses/lib to the args. For some reason, this didn't change anything, until I reinstalled with the --with-s-lang flag. If that had anything to do with it, I have no idea - but now I can see extented characters in neomutt.

**Comment by rlue** [comment]
I can confirm the following (on my machine):

* I have not manually modified the neomutt brew formula in any way.
* `brew install neomutt --with-s-lang` works fine
* `brew rm --force ncurses && brew install neomutt` works fine

  N.b., without homebrew's ncurses package, there is no `libncursesw` file on my computer at all. That is,

      $ sudo find / -name "*libncursesw*"
      $ echo $?
      1

  @andreas-bulling & @flatcap, according to `otool`, neomutt is indeed built against the system version of ncurses, which does not appear to be the wide version (someone please correct me if I'm wrong):

      $ otool -L `which neomutt` | grep curses
              /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)

Definitely a puzzler!

**Comment by VladimirPal** [comment]
Same issue. Nothing of described above didn't helped.

**Comment by gahr** [comment]
Does building with `make EXTRA_CFLAGS=-DNCURSES_WIDECHAR` help?

**Comment by VladimirPal** [comment]
I think my issues was fixed after brew update and reinstall neomutt.
But i'm not sure, because i've tried many different build versions with different args.
At some point, everything worked. i've tried to reproduce the bug, but currently it works with default build. Also i've installed ncurses separately(brew install ncurses), but after uninstall ncurses and rebuild mutt, it still working. Sorry guys, can't give you clear info.

**Comment by gahr** [comment]
@andreas-bulling pull request #908 was merged into master. Could you please try with that?

**Comment by rlue** [comment]
Confirming @VladimirPal's comment.

On a Mac, I saw this issue when the Region (in System Preferences) was set to Taiwan. The output of `locale` is below:

```
$ locale                                                             
LANG=                                                                                   
LC_COLLATE="C"                                                                          
LC_CTYPE="UTF-8"                                                                        
LC_MESSAGES="C"                                                                         
LC_MONETARY="C"                                                                         
LC_NUMERIC="C"                                                                          
LC_TIME="C"                                                                             
LC_ALL=
```

`export LC_ALL=en_us.UTF-8` fixes it, as does switching the region to US in System Preferences. Haven't tried other locales.

**Comment by andreas-bulling** [comment]
I am using the latest version (HEAD as of today) but the problem remains. locale is also set correctly as per @rlue comment.

**Comment by dpgao** [comment]
@rlue's solution above works for me. It seems that in macOS when the system's region-language combination is not present in `locale -a`, `locale` will be set to @rlue's quoted values, breaking `neomutt`'s display.

Interestingly, the latest `mutt` installed from homebrew behaves correctly without changing the locale.

**Comment by libBletchley** [comment]
In the file attachments view I'm seeing filenames like `=?UTF-8?B?yadayadajunkyadayada`.  My setup:
```
$ mutt -D | grep charset
assumed_charset=""
attach_charset=""
charset="utf-8"
config_charset=""
newsgroups_charset="utf-8"
send_charset="us-ascii:iso-8859-1:utf-8"

$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
My attempt to remedy:
```
$ export LC_ALL=en_us.UTF-8
bash: warning: setlocale: LC_ALL: cannot change locale (en_us.UTF-8): No such file or directory
```
This is with NeoMutt 20170113 on Debian Stretch.

**Comment by gahr** [comment]
I think the filename is wrongly encoded using RFC2047 instead of RFC2184. Can you post the source of the email? The mime header for the attachment part should be enough.

**Comment by libBletchley** [comment]
I think this is what you're asking for:
```
[-- Attachment #3: =?UTF-8?B?SGlzdG9yaXF1ZXMgcMOpcmlvZGlxdWVzIGfDqW7DqXJhdXggZHUgMDMuMTIuMjAxOCDDoCAyMy4yMi4wNS5wZGY=?= --]     
[-- Type: application/pgp, Encoding: 8bit, Size: 5.4K --]                                                                                   
```
If I run:
```
perl -MEncode=from_to -pe 'from_to $_, "MIME-Header", "utf-8"' <<< '=?UTF-8?B?SGlzdG9yaXF1ZXMgcMOpcmlvZGlxdWVzIGfDqW7DqXJhdXggZHUgMDMuMTIuMjAxOCDDoCAyMy4yMi4wNS5wZGY=?='
```
I see that the encoding is to support these characters: `é` and `à`

**Comment by gahr** [comment]
> I think this is what you're asking for:

Mh, not exactly. Can you please edit the message (`e` key in the pager) and copy/paste the text in the MIME header?

It should be something like
```
--<your MIME delimiter here>
Content-Type: application/pgp
Content-Disposition: attachment; filename*0*=foobar
...
```

**Comment by libBletchley** [comment]
```
--=_e78d786d697e980fbd21c82cc12950a2
Content-Transfer-Encoding: 8bit
Content-Type: application/pgp; format=text; x-action=encrypt
 name="=?UTF-8?B?SGlzdG9yaXF1ZXMgcMOpcmlvZGlxdWVzIGfDqW7DqXJhdXggZHUgMDMuMTIuMjAxOCDDoCAyMy4yMi4wNS5wZGY=?="; 
Content-Disposition: attachment;
 filename="=?UTF-8?B?SGlzdG9yaXF1ZXMgcMOpcmlvZGlxdWVzIGfDqW7DqXJhdXggZHUgMDMuMTIuMjAxOCDDoCAyMy4yMi4wNS5wZGY=?="; 

-----BEGIN PGP MESSAGE-----
```

**Comment by gahr** [comment]
Thanks - I think the encoding for the `name` and `filename` attributes is wrong, as it's encoded using RFC2047 instead of RFC2184. I'd have to triple check and read some more to state that with certainty, though.

**Comment by libBletchley** [comment]
Sounds reasonable.  The redundancy is certainly disturbing.  Perhaps I need a procmail script to correct it as such messages arrive.

**Comment by gahr** [comment]
https://tools.ietf.org/html/rfc2184#section-4.1 has an example. What mailer has produced these headers? It might be worth upstreaming a patch :)

**Comment by marlun** [comment]
Just to keep anyone else from feeling stupid, please check that you havn't cached the bad headers like I had. Once I'd removed the cache, neomutt displayed the subject correctly.

**Comment by mavam** [comment]
The only way I could get it fixes is by calling (Neo)Mutt like this:
```sh
LC_ALL=en_us.UTF-8 mutt
```

My output of `locale`:
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by yggdr** [comment]
I'm struggling with the same issue here: subject line Umlaute do not work.

```
# neomutt -v
NeoMutt 20220429
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: FreeBSD 13.0-RELEASE-p11 (amd64)
ncurses: ncurses 6.2.20200215 (compiled with 6.2.20200215)
libiconv: 1.16
GPGME: 1.17.1
OpenSSL: OpenSSL 1.1.1k-freebsd  24 Aug 2021
libnotmuch: 5.6.0
PCRE2: 10.40 2022-04-14
storage: tokyocabinet, lmdb

Configure options: --with-ssl=/usr --locales-fix --fmemopen --pcre2 --mandir=/usr/local/man --enable-gpgme --gss --disable-idn --lmdb --enable-nls --enable-notmuch --sasl --tokyocabinet

Compilation CFLAGS: -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include 

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock +fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss 
  +hcache -homespool -idn -inotify +locales_hack -lua -mixmaster +nls +notmuch 
  +openssl +pcre2 +pgp +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

```
# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

```
# ldd `which neomutt` | grep curs
libncursesw.so.9 => /lib/libncursesw.so.9 (0x800ad5000)
```

Any help is appreciated.

**Comment by gahr** [comment]
Can you please try building without `--locales-fix`?

**Comment by yggdr** [comment]
Sadly no change

**Comment by andreas-bulling** [comment]
problem still exists with the latest git version on Ubuntu (compiled from source):

```
$ neomutt -v                                                                                                                                         (main✱)
NeoMutt 20220429-77-e284d5
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.16.15-051615-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGME: 1.13.1-unknown
libnotmuch: 5.2.0
PCRE2: 10.34 2019-11-21
storage: tokyocabinet, lmdb

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --notmuch --gpgme --lua --sasl --tokyocabinet --idn2 --pgp --disable-idn --mixmaster --gss --lmdb --enable-nls --pcre2

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/home/user/src/neomutt-2022.04.29=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss
  +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster +nls +notmuch
  -openssl +pcre2 +pgp +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

```
ldd `which neomutt` | grep curs                                                                                                                    (main✱)
	libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6 (0x00007f64a313a000)
```

```
locale                                                                                                                                             (main✱)
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by flatcap** [comment]
Sorry this has dragged on for so long.
Without being able to reproduce it, it's hard to know what to fix.
However, I might have a clue...

I did a minimal install of Ubuntu 21.04 server, in a VM.
I installed all the dev packages needed, then cloned and built NeoMutt.

My default locale is `LANG=C.UTF-8`
Running NeoMutt, I can enter utf-8 characters using:
- <kbd>AltGr</kbd> + letters
- <kbd>Compose</kbd> + <kbd>"</kbd> + <kbd>a</kbd>

The resulting email has a subject, like: `=?utf-8?B?w6bigJ3CosOwZcOkw6XDog==?=`

So far, so good.

I tried changing my locale: `export LANG=en_GB.utf-8`
but if I check the result (`locale`) it warns me:
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```

If I run NeoMutt again, I **cannot** enter non-ASCII chars (neither <kbd>AltGr</kbd> nor <kbd>Compose</kbd>).

Next I checked which locales were installed: `locale -a`
```
C
C.utf8
POSIX
```

So I installed some: `apt-get install language-pack-en`
This installed and generated all the en_* locales

`locale -a` (abbreviated)
```
C
C.utf8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
...
POSIX
```

Now if I run `locale`, I don't get any warnings.
Finally, I re-ran NeoMutt and it works again.
I can enter non-ASCII chars using <kbd>AltGr</kbd> or <kbd>Compose</kbd>.

**Comment by alexindigo** [comment]
I have something similar.

Seeing `????` instead of cyrillic  characters in the index list of emails.
But only under non-root user, on the same machine (RPi4, Debian Bookworm), under root user I see fine both cyrillic and japanese characters,
and I even tested with the same email to both addresses (root and non-root), and I see utf8 characters under root, not `???` under non-root user.

This is locale for both users:
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by andreas-bulling** [comment]
> Sorry this has dragged on for so long. Without being able to reproduce it, it's hard to know what to fix. However, I might have a clue...
> 
> I did a minimal install of Ubuntu 21.04 server, in a VM. I installed all the dev packages needed, then cloned and built NeoMutt.
> 
> My default locale is `LANG=C.UTF-8` Running NeoMutt, I can enter utf-8 characters using:
> 
>     * AltGr + letters
> 
>     * Compose + " + a
> 
> 
> The resulting email has a subject, like: `=?utf-8?B?w6bigJ3CosOwZcOkw6XDog==?=`
> 
> So far, so good.
> 
> I tried changing my locale: `export LANG=en_GB.utf-8` but if I check the result (`locale`) it warns me:
> 
> ```
> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_MESSAGES to default locale: No such file or directory
> locale: Cannot set LC_ALL to default locale: No such file or directory
> ```
> 
> If I run NeoMutt again, I **cannot** enter non-ASCII chars (neither AltGr nor Compose).
> 
> Next I checked which locales were installed: `locale -a`
> 
> ```
> C
> C.utf8
> POSIX
> ```
> 
> So I installed some: `apt-get install language-pack-en` This installed and generated all the en_* locales
> 
> `locale -a` (abbreviated)
> 
> ```
> C
> C.utf8
> en_AG
> en_AG.utf8
> en_AU.utf8
> en_BW.utf8
> en_CA.utf8
> en_DK.utf8
> en_GB.utf8
> en_HK.utf8
> en_IE.utf8
> ...
> POSIX
> ```
> 
> Now if I run `locale`, I don't get any warnings. Finally, I re-ran NeoMutt and it works again. I can enter non-ASCII chars using AltGr or Compose.

I tried pressing AltGr and a letter together when writing text for the subject but it still doesn't work. I am running the latest version of neomutt, kitty and neovim (even the dev version). Entering Umlaute in neovim directly - no problem. But in the subject line (within neomutt) I simply cannot get it to work :((

Btw - if I compose an email from the command line using the `-s` option I can enter some Umlaute for the subject line and they are also shown correctly after drafting the email. Just entering them when composing an email interactively from within neomutt doesn't work.
